### ISSUE TITLE
Non-default repositories not being setup

### ISSUE THREAD

**Issue by jmacdonald** [datamapper/dm-rails#25]
When trying to use a repository other than the default, I'm getting the following error:

```
Adapter not set: parking. Did you forget to setup?
```

Here's my database.yml file:

```
parking_defaults: &parking_defaults
  adapter:  oracle
  host: server/database
  username: myusername
  password: mypassword

  development:
    <<: *parking_defaults
    repositories:
      parking:
        <<: *parking_defaults
```

I've setup my model to use the _parking_ repository like so:

```
def self.default_repository_name
  :parking
end
```

and I've also set its table name explicitly:

```
storage_names[:parking] = 'TICKETTRANSACTION'
```

If I change both of the _:parking_ symbols in the model to _:default_, everything works as expected.
